//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProdId { get; set; }
        public string ProdName { get; set; }
        public string CateId { get; set; }
        public decimal ProdPrice { get; set; }
        public int ProdSize36Quan { get; set; }
        public int ProdSize37Quan { get; set; }
        public int ProdSize38Quan { get; set; }
        public int ProdSize39Quan { get; set; }
        public string ProdImageUrl { get; set; }

        //public virtual Category Category { get; set; }
        public Category Category { get; set; }
    }
}
